name: Publish Python package to PyPI

on:
  push:
    tags:
      - "v*"    # runs only when you push a tag starting with 'v', e.g. v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # required for OIDC with PyPI
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tool
        run: pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true